export const SET_APP_DATE = "SET_APP_DATE"
export const SET_SELECTED_LOCATION = "SET_SELECTED_LOCATION"
export const GET_MENU_DATA = "GET_MENU_DATA"
export const GET_LOCATION_DATA = "GET_LOCATION_DATA"